Educational_system/Educational_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import index
from Educational_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('system/',include('system.urls')),
    path('student/',include('student.urls')),
    path('teachers/',include('teachers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Educational_system/student/urls.py
from django.urls import path
from .views import (StudentDashboardView,StudentGroupView,StudentLessonView,HomeworkView,HomeDetailView)



app_name = 'student'

urlpatterns = [
    path('dashboard/',StudentDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',StudentGroupView.as_view(),name='gruhlarim'),
    path('lessons/<int:group_id>/',StudentLessonView.as_view(),name='lessons'),
    path('homework/<int:lesson_id>/',HomeworkView.as_view(),name='homework'),
    path('homework-detail/<int:lesson_id>/',HomeDetailView.as_view(),name='homework_detail'),
]

Educational_system/system/urls.py
from django.urls import path
from .views import (LoginView,RegisterView,ProfileView,EditProfileView,LogoutView,GroupsView,StudentsListView,
                    EditStudents,DeleteStudentView,StudentByGroupView,ResetPasswordView)


app_name = 'system'

urlpatterns = [

    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('profile/',ProfileView.as_view(),name='profile'),
    path('edit-profile/',EditProfileView.as_view(),name='edit_profile'),
    path('groups/',GroupsView.as_view(),name='groups'),
    path('students/',StudentsListView.as_view(),name='students'),
    path('student-by-group/<int:id>/',StudentByGroupView.as_view(),name='student_by_group'),
    path('edit-student/<int:id>/',EditStudents.as_view(),name='edit_student'),
    path('delete-student/<int:id>/',DeleteStudentView.as_view(),name='delete_student'),
    path('reset-password/',ResetPasswordView.as_view(),name='reset_password'),

]

Educational_system/teachers/urls.py
from django.urls import path
from .views import (TeacherDashboardView,TeacherGroupView,TeacherGroupLessonView,TeacherHomeworksView,
                    TeacherStudentsView,TeacherCreateLesson)


app_name = 'teachers'

urlpatterns = [
    path('dashboard/',TeacherDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',TeacherGroupView.as_view(),name='gruhlarim'),
    path('gruh/<int:group_id>/',TeacherGroupLessonView.as_view(),name='gruh'),
    path('homework/<int:group_id>/',TeacherHomeworksView.as_view(),name='homework'),
    path('student/<int:group_id>/',TeacherStudentsView.as_view(),name='student'),
    path('create_lesson/<int:group_id>/',TeacherCreateLesson.as_view(),name='create_lesson'),
]

Educational_system/student/models.py
from django.db import models
from system.models import Group,Student



class Lesson(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='lessons')
    title = models.CharField(max_length=150)
    date = models.DateField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)

    class Meta:
        unique_together = ['group','title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.OneToOneField(Lesson,on_delete=models.CASCADE,related_name='homework')
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True,blank=True,related_name='homeworks')
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='students')
    description = models.TextField(null=True,blank=True)
    homework_file = models.FileField(upload_to='homeworks/',blank=True,null=True)
    data = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['student','lesson']

    def __str__(self):
        return f"{self.student.user.first_name}ning {self.lesson.title}  uchun uy vazifasi"

Educational_system/teachers/models.py
from django.db import models

from system.models import User


# Create your models here.

Educational_system/student/forms.py
from django import forms
from .models import Homework

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea)
    homework_file = forms.FileField(widget=forms.FileInput)

Educational_system/teachers/forms.py
from django import forms
from student.models import Lesson


class CreateLessonForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput({"class":"form-control"}))

Educational_system/student/views.py
from django.shortcuts import render, get_object_or_404, redirect
from system.permissions import StudentRequiredMixin
from django.views import View
from system.models import Student,Group
from .models import Lesson,Homework
from .forms import HomeworkForm
class StudentDashboardView(StudentRequiredMixin,View):
    def get(self,request):
        return render(request,'student/dashboard.html')

class StudentGroupView(StudentRequiredMixin,View):
    def get(self,request):
        student = Student.objects.get(user=request.user)
        return render(request,'student/guruhlarim.html',{'student':student})


class StudentLessonView(StudentRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        lessons = group.lessons.all()
        return render(request,'student/lessons.html',{'lessons':lessons})



class HomeworkView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        form = HomeworkForm()
        return render(request,'student/homework.html',{'form':form})

    def post(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student,user=request.user)

        form = HomeworkForm(request.POST,request.FILES)


        if form.is_valid():
            homework = Homework()

            homework.lesson = lesson
            homework.student = student
            homework.description = form.cleaned_data['description']
            homework.homework_file = form.cleaned_data['homework_file']
            homework.save()


            lesson.homework_status = True
            lesson.save()
            return redirect('student:dashboard')



class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        student = get_object_or_404(Student,user=request.user)
        lesson = get_object_or_404(Lesson,id=lesson_id)
        homework = Homework.objects.filter(lesson=lesson,student=student).first()
        return render(request,'student/homework_detail.html',{'homework':homework})

Educational_system/teachers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from system.permissions import TeacherRequiredMixin
# Create your views here.
from django.views import View
from system.models import Teacher,Group
from student.models import Lesson
from .forms import CreateLessonForm
class TeacherDashboardView(TeacherRequiredMixin,View):
    def get(self,request):
        return render(request,'student/dashboard.html')

class TeacherGroupView(TeacherRequiredMixin,View):
    def get(self,request):
        teacher = get_object_or_404(Teacher,user=request.user)
        groups = teacher.groups.all()
        return render(request,'teachers/gruhlarim.html',{'groups':groups})


class TeacherGroupLessonView(TeacherRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        lessons = group.lessons.all()
        return render(request,'teachers/gruh.html',{'group':group,'lessons':lessons})



class TeacherHomeworksView(TeacherRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        lessons = group.homeworks.all()
        return render(request,'teachers/gruh.html',{'group':group,'lessons':lessons})


class TeacherStudentsView(TeacherRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        students = group.students.all()
        return render(request,'teachers/student.html',{'group':group,'students':students})


class TeacherCreateLesson(TeacherRequiredMixin,View):
    def get(self,request,group_id):
        form = CreateLessonForm()
        return render(request,'teachers/create_lesson.html',{'form':form})

    def post(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        form = CreateLessonForm(request.POST)
        if form.is_valid():
            lesson = Lesson()
            lesson.group = group
            lesson.title = form.cleaned_data['title']
            lesson.save()
            url = reverse('teachers:gruh',args=[group_id])
            return redirect(url)
        form = CreateLessonForm()
        return render(request,'teachers/create_lesson.html',{'form':form})

Educational_system/teachers/templates/teachers/create_lesson.html
{% extends 'student/dashboard.html'  %}

{% block content %}

<h1>Create lesson page</h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Save</button>
    </form>

</div>

{% endblock content %}

Educational_system/teachers/templates/teachers/gruh.html
{% extends 'student/dashboard.html' %}

{% block content %}

<h2>{{group.name}}</h2>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button
                data-mdb-collapse-init
                class="navbar-toggler"
                type="button"
                data-mdb-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->

            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:gruh' group.id %}">Darslar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:homework' group.id %}">Uyga vazafalar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Yo'qlama</a>
                </li><li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:student' group.id %}">O'quvchilar</a>
                </li>
            </ul>
               <ul  class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a href="{% url 'teachers:create_lesson' group.id %}" class="btn btn-outline-success">Create lesson</a></li>
               </ul>

            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->


    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->
<br>
<table class="table">
    <thead>
    <tr>

        <th scope="col">Title</th>
        <th scope="col">Date</th>
        <th scope="col"> Status</th>

    </tr>
    </thead>
    <tbody>
    {% for lesson in lessons %}
    <tr class="table-danger">
        {% if lesson.title %}
        <th scope="row">{{lesson.title}}</th>
        {% else %}
        <th scope="row">{{lesson.description}}</th>
        {% endif %}
        <td>{{lesson.date}}</td>
        <td></td>

    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}

Educational_system/teachers/templates/teachers/gruhlarim.html
{% extends 'student/dashboard.html' %}

{% block content %}
<table class="table">
    <thead>
    <tr>

        <th scope="col">Name</th>
        <th scope="col">Yaratilgan vaqti</th>
        <th scope="col"> Status</th>

    </tr>
    </thead>
    <tbody>
    {% for group in groups %}
    <tr class="table-danger">
        <th scope="row"><a href="{% url 'teachers:gruh' group.id %}">{{group.name}}</a></th>
        <td>{{group.data_created}}</td>
        <td>active</td>

    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}

Educational_system/teachers/templates/teachers/homework.html
{% extends 'student/dashboard.html' %}

{% block content %}

<h2>{{group.name}}</h2>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button
                data-mdb-collapse-init
                class="navbar-toggler"
                type="button"
                data-mdb-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->

            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:gruh' group.id %}">Darslar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:homework' group.id %}">Uyga vazafalar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Yo'qlama</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'teachers:student' group.id %}">O'quvchilar</a>
            </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->


    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->
<br>
<table class="table">
    <thead>
    <tr>

        <th scope="col">Title</th>
        <th scope="col">Date</th>
        <th scope="col"> Status</th>

    </tr>
    </thead>
    <tbody>
    {% for lesson in lessons %}
    <tr class="table-danger">
        {% if lesson.title %}
        <th scope="row">{{lesson.title}}</th>
        {% else %}
        <th scope="row">{{lesson.description}}</th>
        {% endif %}
        <td>{{lesson.date}}</td>
        <td></td>

    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}

Educational_system/teachers/templates/teachers/student.html
{% extends 'student/dashboard.html' %}

{% block content %}

<h2>{{group.name}}</h2>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button
                data-mdb-collapse-init
                class="navbar-toggler"
                type="button"
                data-mdb-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->

            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:gruh' group.id %}">Darslar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:homework' group.id %}">Uyga vazafalar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Yo'qlama</a>
                </li><li class="nav-item">
                <a class="nav-link" href="{% url 'teachers:student' group.id %}">O'quvchilar</a>
            </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->


    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->
<br>
<table class="table">
    <thead>
    <tr>

        <th scope="col">First_name</th>
        <th scope="col">Group</th>
        <th scope="col"></th>

    </tr>
    </thead>
    <tbody>
    {% for student in students %}
    <tr class="table-danger">

        <th scope="row">{{student.user.first_name}}</th>

        <th scope="row">{{student.group.name}}</th>


        <td></td>

    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}