Educational_system/Educational_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import index
from Educational_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('system/',include('system.urls')),
    path('student/',include('student.urls')),
    path('teachers/',include('teachers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Educational_system/student/urls.py
from django.urls import path
from .views import (StudentDashboardView,StudentGroupView,StudentLessonView,HomeworkView,HomeDetailView)



app_name = 'student'

urlpatterns = [
    path('dashboard/',StudentDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',StudentGroupView.as_view(),name='gruhlarim'),
    path('lessons/<int:group_id>/',StudentLessonView.as_view(),name='lessons'),
    path('homework/<int:lesson_id>/',HomeworkView.as_view(),name='homework'),
    path('homework-detail/<int:lesson_id>/',HomeDetailView.as_view(),name='homework_detail'),
]

Educational_system/system/urls.py
from django.urls import path
from .views import (LoginView,RegisterView,ProfileView,EditProfileView,LogoutView,GroupsView,StudentsListView,
                    EditStudents,DeleteStudentView,StudentByGroupView,ResetPasswordView)


app_name = 'system'

urlpatterns = [

    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('profile/',ProfileView.as_view(),name='profile'),
    path('edit-profile/',EditProfileView.as_view(),name='edit_profile'),
    path('groups/',GroupsView.as_view(),name='groups'),
    path('students/',StudentsListView.as_view(),name='students'),
    path('student-by-group/<int:id>/',StudentByGroupView.as_view(),name='student_by_group'),
    path('edit-student/<int:id>/',EditStudents.as_view(),name='edit_student'),
    path('delete-student/<int:id>/',DeleteStudentView.as_view(),name='delete_student'),
    path('reset-password/',ResetPasswordView.as_view(),name='reset_password'),

]

Educational_system/teachers/urls.py
from django.urls import path
from .views import (TeacherDashboardView,TeacherGroupView,TeacherGroupLessonView,TeacherHomeworksView,
                    TeacherStudentsView,TeacherCreateLesson)


app_name = 'teachers'

urlpatterns = [
    path('dashboard/',TeacherDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',TeacherGroupView.as_view(),name='gruhlarim'),
    path('gruh/<int:group_id>/',TeacherGroupLessonView.as_view(),name='gruh'),
    path('homework/<int:group_id>/',TeacherHomeworksView.as_view(),name='homework'),
    path('student/<int:group_id>/',TeacherStudentsView.as_view(),name='student'),
    path('create_lesson/<int:group_id>/',TeacherCreateLesson.as_view(),name='create_lesson'),
]

Educational_system/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


    <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
            rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"
    />
    <!-- MDB -->
    <link
            href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css"
            rel="stylesheet"
    />


    <title>Title</title>
</head>
<body>

<div class="container py-5">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb" class="bg-body-tertiary rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">

                    {% if user.is_authenticated %}
                    <li class="breadcrumb-item"><a href="{% url 'system:logout' %}">Logout</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'system:profile' %}">User profile</a></li>
                    {% if user.user_role == 'admin' %}
                    <li class="breadcrumb-item"><a href="{% url 'system:register' %}">Register</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'system:groups' %}">Groups</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'system:students' %}">Students</a></li>
                    {% endif %}

                    {% if user.user_role == 'student' %}
                    <li class="breadcrumb-item"><a href="{% url 'student:dashboard' %}">Dashboard</a></li>
                    {% else %}
                    <li class="breadcrumb-item"><a href="{% url 'teachers:dashboard' %}">Dashboard</a></li>

                    {% endif %}


                    {% else %}
                    <li class="breadcrumb-item"><a href="{% url 'system:login' %}">Log in</a></li>
                    {% endif %}
                </ol>
            </nav>
        </div>
    </div>


    {% block content %}
    {% endblock content %}

</div>


<!-- MDB -->
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
></script>
</body>
</html>

Educational_system/templates/index.html
{% extends 'base.html'  %}

{% block content %}
<h1> This is Home page </h1>

{% endblock content %}