Educational_system/Educational_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import index
from Educational_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('system/',include('system.urls')),
    path('student/',include('student.urls')),
    path('teachers/',include('teachers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Educational_system/student/urls.py
from django.urls import path
from .views import (StudentDashboardView,StudentGroupView,StudentLessonView,HomeworkView,HomeDetailView)



app_name = 'student'

urlpatterns = [
    path('dashboard/',StudentDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',StudentGroupView.as_view(),name='gruhlarim'),
    path('lessons/<int:group_id>/',StudentLessonView.as_view(),name='lessons'),
    path('homework/<int:lesson_id>/',HomeworkView.as_view(),name='homework'),
    path('homework-detail/<int:lesson_id>/',HomeDetailView.as_view(),name='homework_detail'),
]

Educational_system/system/urls.py
from django.urls import path
from .views import (LoginView,RegisterView,ProfileView,EditProfileView,LogoutView,GroupsView,StudentsListView,
                    EditStudents,DeleteStudentView,StudentByGroupView,ResetPasswordView)


app_name = 'system'

urlpatterns = [

    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('profile/',ProfileView.as_view(),name='profile'),
    path('edit-profile/',EditProfileView.as_view(),name='edit_profile'),
    path('groups/',GroupsView.as_view(),name='groups'),
    path('students/',StudentsListView.as_view(),name='students'),
    path('student-by-group/<int:id>/',StudentByGroupView.as_view(),name='student_by_group'),
    path('edit-student/<int:id>/',EditStudents.as_view(),name='edit_student'),
    path('delete-student/<int:id>/',DeleteStudentView.as_view(),name='delete_student'),
    path('reset-password/',ResetPasswordView.as_view(),name='reset_password'),

]

Educational_system/student/models.py
from django.db import models
from system.models import Group,Student



class Lesson(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='lessons')
    title = models.CharField(max_length=150)
    date = models.DateField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)

    class Meta:
        unique_together = ['group','title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.OneToOneField(Lesson,on_delete=models.CASCADE,related_name='homework')
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True,blank=True,related_name='homeworks')
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='students')
    description = models.TextField(null=True,blank=True)
    homework_file = models.FileField(upload_to='homeworks/',blank=True,null=True)
    data = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['student','lesson']

    def __str__(self):
        return f"{self.student.user.first_name}ning {self.lesson.title}  uchun uy vazifasi"

Educational_system/system/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    USER_ROLE_CHOICES = [
        ('student', "Student"),
        ('teacher', "Teacher"),
        ('admin', "Admin")
    ]
    image = models.ImageField(upload_to='profile_pics/',blank=True,null=True,default='profile_pics/default.jpg')
    phone_number = models.CharField(max_length=13,null=True,blank=True)
    address = models.CharField(max_length=200,null=True,blank=True)
    user_role = models.CharField(max_length=200,choices=USER_ROLE_CHOICES,default="student")

class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth = models.DateField(null=True,blank=True)
    def __str__(self):
        return self.user.username

class Group(models.Model):
    name = models.CharField(max_length=100,unique=True)
    data_created = models.DateTimeField(auto_now_add=True)
    end_data = models.DateTimeField(blank=True,null=True)
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE,related_name='groups',null=True,blank=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True,null=True)
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='students',null=True,blank=True)

    def __str__(self):
        return self.user.first_name

Educational_system/student/forms.py
from django import forms
from .models import Homework

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea)
    homework_file = forms.FileField(widget=forms.FileInput)

Educational_system/system/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User, Student

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, min_length=4, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(widget=forms.TextInput({'class': 'form-control width', 'type': 'password'}))

class RegisterForm(forms.ModelForm):
    USER_ROLE_CHOICES = [
        ('student', "Student"),
        ('teacher', "Teacher"),
        ('admin', "Admin")
    ]

    password = forms.CharField(max_length=100, min_length=6, widget=forms.PasswordInput({'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=100, min_length=6, widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password', 'confirm_password', 'user_role')

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return confirm_password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'address', 'image', 'phone_number', 'email')

class StudentEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput({"class":"form-control"}))


    class Meta:
        model = Student
        fields = ('date_of_birth', 'group')

class ResetPasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput({'class': 'form-control',"placeholder":"old_password"}))
    new_password = forms.CharField(widget=forms.PasswordInput({'class': 'form-control',"placeholder":"new_password"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput({'class': 'form-control',"placeholder":"confirm_password"}))

    def clean_confirm_password(self):
        new_password = self.cleaned_data['new_password']
        confirm_password = self.cleaned_data['confirm_password']

        if new_password != confirm_password:
            raise forms.ValidationError("Passwords don't match")
        return confirm_password

Educational_system/student/views.py
from django.shortcuts import render, get_object_or_404, redirect
from system.permissions import StudentRequiredMixin
from django.views import View
from system.models import Student,Group
from .models import Lesson,Homework
from .forms import HomeworkForm
class StudentDashboardView(StudentRequiredMixin,View):
    def get(self,request):
        return render(request,'student/dashboard.html')

class StudentGroupView(StudentRequiredMixin,View):
    def get(self,request):
        student = Student.objects.get(user=request.user)
        return render(request,'student/guruhlarim.html',{'student':student})


class StudentLessonView(StudentRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        lessons = group.lessons.all()
        return render(request,'student/lessons.html',{'lessons':lessons})



class HomeworkView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        form = HomeworkForm()
        return render(request,'student/homework.html',{'form':form})

    def post(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student,user=request.user)

        form = HomeworkForm(request.POST,request.FILES)


        if form.is_valid():
            homework = Homework()

            homework.lesson = lesson
            homework.student = student
            homework.description = form.cleaned_data['description']
            homework.homework_file = form.cleaned_data['homework_file']
            homework.save()


            lesson.homework_status = True
            lesson.save()
            return redirect('student:dashboard')



class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        student = get_object_or_404(Student,user=request.user)
        lesson = get_object_or_404(Lesson,id=lesson_id)
        homework = Homework.objects.filter(lesson=lesson,student=student).first()
        return render(request,'student/homework_detail.html',{'homework':homework})

Educational_system/system/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .permissions import AdminRequiredMixin
from .forms import LoginForm, RegisterForm, ProfileEditForm, StudentEditForm,ResetPasswordForm
from .models import User, Student, Group,Teacher
from django.db.models import Q

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'system/login.html', context={'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('system:profile')
        return render(request, 'system/login.html', context={'form': form})

class RegisterView(AdminRequiredMixin, View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'system/register.html', context={'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user.user_role == 'student':
                new_student = Student(user=user)
                new_student.save()
            elif user.user_role == 'teacher':
                new_teacher = Teacher(user=user)
                new_teacher.save()
            return redirect('/')
        return render(request, 'system/register.html', context={'form': form})

class ProfileView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'system/profile.html', context={'user': request.user})

class EditProfileView(LoginRequiredMixin, View):
    def get(self, request):
        form = ProfileEditForm(instance=request.user)
        return render(request, 'system/edit_profile.html', {'form': form})

    def post(self, request):
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('system:profile')
        return render(request, 'system/edit_profile.html', {'form': form})

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/')

class GroupsView(View):
    def get(self, request):
        groups = Group.objects.all()
        return render(request, 'system/groups.html', {'groups': groups})

class StudentsListView(AdminRequiredMixin, View):
    def get(self, request):
        if request.GET != {}:
            students = Student.objects.filter(Q(user__username__icontains = request.GET['search']) | Q(group__name__icontains= request.GET['search'])
                                              | Q(user__first_name__icontains= request.GET['search']) | Q(user__last_name__icontains= request.GET['search']))
        else:
            students = Student.objects.all()
        return render(request, 'system/students.html', {'students': students})

class StudentByGroupView(AdminRequiredMixin,View):
    def get(self,request,id):
        group = get_object_or_404(Group,id=id)
        students = group.students.all()
        return render(request, 'system/students.html', {'students': students})


class EditStudents(AdminRequiredMixin, View):
    def get(self, request, id):
        student = get_object_or_404(Student, id=id)
        form = StudentEditForm(instance=student)
        return render(request, 'system/edit_student.html', {'form': form})

    def post(self, request, id):
        student = get_object_or_404(Student, id=id)
        form = StudentEditForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('system:students')
        return render(request, 'system/edit_student.html', {'form': form})


class DeleteStudentView(AdminRequiredMixin,View):
    def get(self,request,id):
        student = get_object_or_404(Student,id=id)
        user = User.objects.get(username=student.user.username)
        student.delete()
        user.delete()
        return redirect('system:students')

class ResetPasswordView(LoginRequiredMixin,View):
    def get(self,request):
        form = ResetPasswordForm()
        return render(request,'system/reset_password.html',{'form':form})

Educational_system/system/templates/system/edit_profile.html
{% extends 'base.html'  %}

{% block content %}

<h1>Edit Profile page</h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Save</button>
    </form>

</div>

{% endblock content %}

Educational_system/system/templates/system/edit_student.html
{% extends 'base.html'  %}

{% block content %}

<h1>Edit Student page</h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Save</button>
    </form>

</div>

{% endblock content %}

Educational_system/system/templates/system/groups.html
{% extends 'base.html'  %}

{% block content %}


<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
    <tr>

        <th>Title</th>
        <th>Status</th>

        <th>Students</th>
    </tr>
    </thead>
    <tbody>
    {% for group in groups %}
    <tr>

        <td>
            <p class="fw-normal mb-1">{{group.name}}</p>

        </td>
        <td>
            <span class="badge badge-success rounded-pill d-inline">Active</span>
        </td>
        
        <td>
            <a href="{% url 'system:student_by_group' group.id %}" class="btn btn-link btn-sm btn-rounded">
               Show students
            </a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}

Educational_system/system/templates/system/login.html
{% extends 'base.html'  %}

{% block content %}

<h1>Login qismi</h1>
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Login</button>
    </form>

</div>

{% endblock content %}

Educational_system/system/templates/system/profile.html
{% extends 'base.html' %}


{% block content %}
<section style="background-color: #eee;">



        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="{{ user.image.url }}" alt="avatar"
                             class="rounded-circle img-fluid" style="width: 150px;">
                        <h5 class="my-3">{{user.first_name}} | {{user.last_name}}</h5>
                        <p class="text-muted mb-1">{{user.phone_number}}</p>
                        <p class="text-muted mb-4">{{user.address}}</p>
                        <div class="d-flex justify-content-center mb-2">
                            <a href="{% url 'system:reset_password' %}"  class="btn btn-primary">Reset password</a>
                            <a href="{% url 'system:edit_profile' %}"  class="btn btn-outline-primary ms-1">Edit</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.first_name}} | {{user.last_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.address}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Phone</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.phone_number}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Mobile</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.phone_number}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Address</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.address}}</p>
                            </div>
                        </div>
                    </div>
                </div>
        
            </div>
        </div>

</section>
{% endblock content %}

Educational_system/system/templates/system/register.html
{% extends 'base.html'  %}

{% block content %}

<h1>Register qismi</h1>
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Register</button>
    </form>

</div>

{% endblock content %}

Educational_system/system/templates/system/reset_password.html
{% extends 'student/dashboard.html'  %}

{% block content %}

<h1>Reset password page</h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-outline-success">Save</button>
    </form>

</div>

{% endblock content %}

Educational_system/system/templates/system/students.html
{% extends 'base.html'  %}

{% block content %}

<div class="input-group rounded">
    <form method="get">
        <div class="input-group">
            <input type="search" class="form-control rounded" name="search" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            <button type="submit" class="btn btn-outline-primary" data-mdb-ripple-init>search</button>
        </div>
    </form>
</div>

<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
    <tr>
        <th>Full Name</th>
        <th>Username</th>
        <th>Group</th>
        <th>Actions</th>

    </tr>
    </thead>
    <tbody>
    {% for student in students %}
    <tr>
        <td>
            <div class="d-flex align-items-center">
                <img
                        src="{{student.user.image.url}}"
                        alt=""
                        style="width: 45px; height: 45px"
                        class="rounded-circle"
                />
                <div class="ms-3">
                    <p class="fw-bold mb-1">{{student.user.first_name}} {{student.user.last_name}}</p>
                    <p class="text-muted mb-0">{{student.user.email}}</p>
                </div>
            </div>
        </td>
        <td>
            <p class="fw-normal mb-1">{{student.user.username}}</p>

        </td>

        <td class="fw-normal mb-1">{{student.group}}</td>

        <td>
            <a href="{% url 'system:edit_student' student.id %}" class="btn btn-outline-info">
                Edit
            </a><a href="{% url 'system:delete_student' student.id %}" class="btn btn-outline-danger">
                Delete
            </a>
        </td>

    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock content %}