Educational_system/Educational_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import index
from Educational_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('system/',include('system.urls')),
    path('student/',include('student.urls')),
    path('teachers/',include('teachers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Educational_system/student/urls.py
from django.urls import path
from .views import (StudentDashboardView,StudentGroupView,StudentLessonView,HomeworkView,HomeDetailView)



app_name = 'student'

urlpatterns = [
    path('dashboard/',StudentDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',StudentGroupView.as_view(),name='gruhlarim'),
    path('lessons/<int:group_id>/',StudentLessonView.as_view(),name='lessons'),
    path('homework/<int:lesson_id>/',HomeworkView.as_view(),name='homework'),
    path('homework-detail/<int:lesson_id>/',HomeDetailView.as_view(),name='homework_detail'),
]

Educational_system/system/urls.py
from django.urls import path
from .views import (LoginView,RegisterView,ProfileView,EditProfileView,LogoutView,GroupsView,StudentsListView,
                    EditStudents,DeleteStudentView,StudentByGroupView,ResetPasswordView)


app_name = 'system'

urlpatterns = [

    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('profile/',ProfileView.as_view(),name='profile'),
    path('edit-profile/',EditProfileView.as_view(),name='edit_profile'),
    path('groups/',GroupsView.as_view(),name='groups'),
    path('students/',StudentsListView.as_view(),name='students'),
    path('student-by-group/<int:id>/',StudentByGroupView.as_view(),name='student_by_group'),
    path('edit-student/<int:id>/',EditStudents.as_view(),name='edit_student'),
    path('delete-student/<int:id>/',DeleteStudentView.as_view(),name='delete_student'),
    path('reset-password/',ResetPasswordView.as_view(),name='reset_password'),

]

Educational_system/teachers/urls.py
from django.urls import path
from .views import (TeacherDashboardView,TeacherGroupView,TeacherGroupLessonView,TeacherHomeworksView,
                    TeacherStudentsView,TeacherCreateLesson)


app_name = 'teachers'

urlpatterns = [
    path('dashboard/',TeacherDashboardView.as_view(),name='dashboard'),
    path('gruhlarim/',TeacherGroupView.as_view(),name='gruhlarim'),
    path('gruh/<int:group_id>/',TeacherGroupLessonView.as_view(),name='gruh'),
    path('homework/<int:group_id>/',TeacherHomeworksView.as_view(),name='homework'),
    path('student/<int:group_id>/',TeacherStudentsView.as_view(),name='student'),
    path('create_lesson/<int:group_id>/',TeacherCreateLesson.as_view(),name='create_lesson'),
]

Educational_system/student/models.py
from django.db import models
from system.models import Group,Student



class Lesson(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='lessons')
    title = models.CharField(max_length=150)
    date = models.DateField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)

    class Meta:
        unique_together = ['group','title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.OneToOneField(Lesson,on_delete=models.CASCADE,related_name='homework')
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True,blank=True,related_name='homeworks')
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='students')
    description = models.TextField(null=True,blank=True)
    homework_file = models.FileField(upload_to='homeworks/',blank=True,null=True)
    data = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['student','lesson']

    def __str__(self):
        return f"{self.student.user.first_name}ning {self.lesson.title}  uchun uy vazifasi"

Educational_system/student/forms.py
from django import forms
from .models import Homework

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea)
    homework_file = forms.FileField(widget=forms.FileInput)

Educational_system/student/views.py
from django.shortcuts import render, get_object_or_404, redirect
from system.permissions import StudentRequiredMixin
from django.views import View
from system.models import Student,Group
from .models import Lesson,Homework
from .forms import HomeworkForm
class StudentDashboardView(StudentRequiredMixin,View):
    def get(self,request):
        return render(request,'student/dashboard.html')

class StudentGroupView(StudentRequiredMixin,View):
    def get(self,request):
        student = Student.objects.get(user=request.user)
        return render(request,'student/guruhlarim.html',{'student':student})


class StudentLessonView(StudentRequiredMixin,View):
    def get(self,request,group_id):
        group = get_object_or_404(Group,id=group_id)
        lessons = group.lessons.all()
        return render(request,'student/lessons.html',{'lessons':lessons})



class HomeworkView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        form = HomeworkForm()
        return render(request,'student/homework.html',{'form':form})

    def post(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student,user=request.user)

        form = HomeworkForm(request.POST,request.FILES)


        if form.is_valid():
            homework = Homework()

            homework.lesson = lesson
            homework.student = student
            homework.description = form.cleaned_data['description']
            homework.homework_file = form.cleaned_data['homework_file']
            homework.save()


            lesson.homework_status = True
            lesson.save()
            return redirect('student:dashboard')



class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        student = get_object_or_404(Student,user=request.user)
        lesson = get_object_or_404(Lesson,id=lesson_id)
        homework = Homework.objects.filter(lesson=lesson,student=student).first()
        return render(request,'student/homework_detail.html',{'homework':homework})

Educational_system/student/templates/student/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <!-- Font Awesome -->
    <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
            rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"
    />
    <!-- MDB -->
    <link
            href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css"
            rel="stylesheet"
    />
    <title>Title</title>
</head>
<body>


<!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                {% if user.user_role == 'teacher' %}
                <a
                        href="{% url 'teachers:dashboard' %}"
                        class="list-group-item list-group-item-action py-2 ripple"
                        aria-current="true"
                >
                    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Main dashboard</span>
                </a>
                {% else %}
                <a
                        href="{% url 'student:dashboard' %}"
                        class="list-group-item list-group-item-action py-2 ripple"
                        aria-current="true"
                >
                    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Main dashboard</span>
                </a>
                {% endif %}
                {% if user.user_role == 'teacher' %}
                <a href="{% url 'teachers:gruhlarim' %}" class="list-group-item list-group-item-action py-2 ripple"
                ><i class="fas fa-lock fa-fw me-3"></i><span>Gruhlarim</span></a
                >
                {% else %}


                <a href="{% url 'student:gruhlarim' %}" class="list-group-item list-group-item-action py-2 ripple"
                ><i class="fas fa-lock fa-fw me-3"></i><span>Gruhlarim</span></a
                >
                <a href="#" class="list-group-item list-group-item-action py-2 ripple active">
                    <i class="fas fa-chart-area fa-fw me-3"></i><span>To'lovlarim</span>
                </a>
                {% endif %}
<!--
            </div>
        </div>
    </nav>
    <!-- Sidebar -->

    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button data-mdb-button-init
                    class="navbar-toggler"
                    type="button"
                    data-mdb-collapse-init
                    data-mdb-target="#sidebarMenu"
                    aria-controls="sidebarMenu"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
            >
                <i class="fas fa-bars"></i>
            </button>

            <!-- Brand -->
            <a class="navbar-brand" href="#">
                <img
                        src="{% static 'images/logo.jpeg' %}"
                        height="55"
                        alt="Avatar"
                        loading="lazy"
                />
            </a>
            <!-- Search form -->


            <!-- Right links -->
            <ul class="navbar-nav ms-auto d-flex flex-row">






                <!-- Avatar -->
                <li class="nav-item dropdown">
                    <a
                            data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
                            href="#"
                            id="navbarDropdownMenuLink"
                            role="button"
                            data-mdb-toggle="dropdown"
                            aria-expanded="false"
                    >
                        <img
                                src="{{user.image.url}}"
                                class="rounded-circle"
                                height="50px"
                                alt="Avatar"
                                loading="lazy"

                        />
                    </a>
                    <ul
                            class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuLink"
                    >
                        <li>
                            <a class="dropdown-item" href="{% url 'system:profile' %}">My profile</a>
                        </li>

                        <li>
                            <a class="dropdown-item" href="{% url 'system:logout' %}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block content %}
        {% endblock content %}
    </div>
</main>
<!--Main layout-->




<!-- MDB -->
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
></script>
</body>
</html>

Educational_system/student/templates/student/guruhlarim.html
{% extends 'student/dashboard.html' %}

{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>

    </tr>
    </thead>
    <tbody>

    <tr class="table-danger">
        <th scope="row">{{student.group.id}}</th>
        <td><a href="{% url 'student:lessons' student.group.id %}">{{student.group.name}}</a></td>
        <td>active</td>

    </tr>

    </tbody>
</table>

{% endblock content %}

Educational_system/student/templates/student/homework.html
{% extends 'student/dashboard.html' %}

{% block content %}


<h1>Homework qismi</h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-outline-success">Upload</button>
    </form>

</div>


{% endblock content %}

Educational_system/student/templates/student/homework_detail.html
{% extends 'student/dashboard.html' %}

{% block content %}


<h1>Homework qismi</h1>
<div class="container mt-5">
    <table class="table">
        <thead>
        <tr>

            <th scope="col">Title</th>
            <th scope="col"> Description</th>
            <th scope="col"> File</th>


        </tr>
        </thead>
        <tbody>

        <tr class="table-danger">
            <th scope="row">{{homework.lesson.title}}</th>
            <td>{{homework.description}}</td>
            <td><a href="{{homework.homework_file.url}}" download>{{homework.homework_file}}</a></td>


        </tr>

        </tbody>
    </table>
</div>


{% endblock content %}

Educational_system/student/templates/student/lessons.html
{% extends 'student/dashboard.html' %}

{% block content %}
<table class="table">
  <thead>
  <tr>

    <th scope="col">Title</th>
    <th scope="col"> Date</th>
    <th scope="col">Homework Status</th>


  </tr>
  </thead>
  <tbody>
  {% for lesson in lessons %}
  <tr class="table-danger">
    <th scope="row">{{lesson.title}}</th>
    <td>{{lesson.date}}</td>
    <td>{% if lesson.homework_status %}<a href="{% url 'student:homework_detail' lesson.id %}" class="btn btn-success">Bajarilgan</> {% else %}<a href="{% url 'student:homework' lesson.id %}" class="btn btn-danger">Bajarilmagan</a>{% endif %} </td>
    {% endfor %}

  </tr>

  </tbody>
</table>

{% endblock content %}